name: Check Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prettier:
    name: Lint prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - name: Run Prettier
        run: npx prettier . --check
